lab_ppw/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story_1/', include('story_1.urls')),
    path('story_3/', include('story_3.urls')),
    path('story_4/', include('story_4.urls')),
    path('story_5/', include('story_5.urls')),
    path('story_8/', include('story_8.urls')),
    path('', include('story_7.urls'))
]

story_1/urls.py
from django.urls import path
from . import views

app_name = 'story_1'

urlpatterns = [
    path('', views.index, name='index'),
]

story_3/urls.py
from os import name, pardir
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='story-3'),
    path('gallery', views.gallery)
]

story_4/urls.py
from os import name, pardir
from django.urls import path
from . import views

app_name = 'story_4'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery', views.gallery, name='gallery')
]

story_5/urls.py
from os import name, pardir
from django.urls import path
from . import views

app_name = 'story_5'

urlpatterns = [
    path('', views.list_matkul, name='list_matkul'),
    path('new/', views.form, name='form'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('delete/<int:id>', views.delete, name='delete'),
]

story_7/urls.py
from os import name, pardir
from django.urls import path
from . import views

app_name = 'story_7'

urlpatterns = [
    path('', views.index, name='index')
]

story_8/urls.py
from os import name, pardir
from django.urls import path
from . import views

app_name = 'story_8'

urlpatterns = [
    path('', views.index, name='index'),
    path('<keyword>', views.get_book, name="get_book")
]

story_1/models.py
from django.db import models

# Create your models here.

story_3/models.py
from django.db import models

# Create your models here.

story_4/models.py
from django.db import models

# Create your models here.

story_5/models.py
from django.db import models

# Create your models here.


class MataKuliah(models.Model):
    nama = models.CharField(max_length=50, default="Kosong")
    dosen_pengajar = models.CharField(max_length=30, default="Kosong")
    jumlah_sks = models.IntegerField(default=0)
    deskripsi = models.CharField(max_length=100, default="Kosong")
    tahun_ajar = models.CharField(max_length=20, default="Kosong")
    ruang_kelas = models.CharField(max_length=20, default="Kosong")

story_7/models.py
from django.db import models

# Create your models here.

story_8/models.py
from django.db import models

# Create your models here.

story_5/forms.py
from django import forms
from .models import MataKuliah


class Input_Form(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = ['nama', 'dosen_pengajar', 'jumlah_sks',
                  'deskripsi', 'tahun_ajar', 'ruang_kelas']

    error_messages = {
        'required': 'Please Type'
    }

    nama = forms.CharField(label='nama', max_length=50, widget=forms.TextInput(
        attrs={'type': 'text'}))
    dosen_pengajar = forms.CharField(label='dosen', max_length=30, widget=forms.TextInput(
        attrs={'type': 'text'}))
    jumlah_sks = forms.IntegerField(widget=forms.TextInput(
        attrs={'type': 'number', 'min': 0, 'max': 24}))
    deskripsi = forms.CharField(label='deskripsi', max_length=100, widget=forms.TextInput(
        attrs={'type': 'text'}))
    tahun_ajar = forms.CharField(label='tahun', max_length=20, widget=forms.TextInput(
        attrs={'type': 'text', 'placeholder': 'Gasal 2019/2020'}))
    ruang_kelas = forms.CharField(label='kelas', max_length=20, widget=forms.TextInput(
        attrs={'type': 'text'}))

story_1/views.py
from django.shortcuts import render

mhs_name = 'Muhammad Fathan Muthahhari'
npm = 1906293190

# Create your views here.


def index(request):
    response = {'name': mhs_name, 'npm': npm, 'story': 1}
    return render(request, 'index_lab1.html', response)

story_3/views.py
from django.http import request
from django.http import response
from django.shortcuts import render

mhs_name = 'Muhammad Fathan Muthahhari'

# Create your views here.


def index(request):
    response = {'name': mhs_name}
    return render(request, 'index_lab3.html', response)


def gallery(request):
    return render(request, 'lab3_new_page.html')

story_4/views.py
from django.http import request
from django.http import response
from django.shortcuts import render

mhs_name = 'Muhammad Fathan Muthahhari'

# Create your views here.


response = {'name': mhs_name, 'story': 4}


def index(request):
    return render(request, 'index_lab4.html', response)


def gallery(request):
    return render(request, 'lab4_new_page.html', response)

story_5/views.py
from django.db.models.query import NamedValuesListIterable
from django.http import response
from django.http import request
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from .models import MataKuliah
from .forms import Input_Form

# Create your views here.


def form(request):
    return render(request, 'form.html', {'form': Input_Form})


def list_matkul(request):
    form = Input_Form(request.POST or None)
    matkuls = MataKuliah.objects.all()
    if(form.is_valid and request.method == 'POST'):
        form.save()
    return render(request, 'list_matkul.html', {'matkuls': matkuls})


def update(request):
    return render(request, 'form.html', {'form': Input_Form})


def delete(request, id):
    p = MataKuliah.objects.get(id=id)
    MataKuliah.delete(p)
    return HttpResponseRedirect('/story_5')


def detail(request, id):
    p = MataKuliah.objects.get(id=id)
    return render(request, 'detail.html', {'matkul': p})

story_7/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story_7.html')

story_8/views.py
from django.shortcuts import render
import requests
from django.http.response import JsonResponse

# Create your views here.
def index(request):
    return render(request, 'story_8.html')

def get_book(request, keyword):
    url = f"https://www.googleapis.com/books/v1/volumes?q={keyword}"
    response = requests.get(url).json()
    return JsonResponse(response)

story_1/templates/index_lab1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Story 1: {{ name }}</title>
    <link rel="stylesheet" href="{% static './css/all.css' %}" />
  </head>
  <body>
    <a href="{% url 'story_4:index'%}">Go to Story 4</a>
    <div>
      <h1>Hello my name is {{ name }}</h1>
      <h3>NPM: {{ npm }}</h3>
      <h3>Maung 19</h3>
    </div>
    <div>
      <img
        src="{% static './JP34-min.jpg' %}"
        alt="Fathan Muthahhari"
        style="max-width: 300px"
      />
      <h1>About Me!</h1>
      <p>
        I am an active learner that always keen to learn more about how things
        work. Love anything associated with asthethic and creativity.
      </p>
    </div>
    <div>
      <h1>Interest</h1>
      <ul>
        <li>Graphic Design</li>
        <li>Indie Games</li>
        <li>Software Development</li>
        <li>F1</li>
      </ul>
    </div>
    <div>
      <h1>Education:</h1>
      <ol>
        <li>2008 - 2013: Sekolah Alam Bogor</li>
        <li>2013 - 2016: SMPN 4 Bogor</li>
        <li>2016 - 2019: SMAN 1 Bogor</li>
        <li>
          2019 - 2023 (expected): Faculty of Computer Science, University of
          Indonesia
        </li>
      </ol>
    </div>
    <div>
      <h1>Keep in Touch with Me</h1>
      <ul>
        <li><i class="fas fa-envelope"></i>: fathanmuthahhari@gmail.com</li>
        <li>
          <a href="https://www.instagram.com/fathanmuthahhari/"
            ><i class="fab fa-instagram"></i
          ></a>
        </li>
        <li>
          <a href="https://www.linkedin.com/in/muhammad-fathan-m-a45684130/"
            ><i class="fab fa-linkedin"></i
          ></a>
        </li>
      </ul>
    </div>
  </body>
</html>

story_3/templates/index_lab3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Story 3: {{ name }}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static './css/all.css' %}" />
    <link rel="stylesheet" href="{% static './css/style.css' %}" />
  </head>
  <body>
    <nav>
      <ul class="menu">
        <li><a href="#about">HOME</a></li>
        <li><a href="#resume">RESUME</a></li>
        <li><a href="#contacts">CONTACTS</a></li>
        <!-- <li><a href="/gallery">GALLERY</a></li> -->
      </ul>
    </nav>

    <div class="landing">
      <div class="opening">
        <h1>Hello, I'm <span class="name">{{ name }}</span></h1>
        <p>Computer science student at University of Indonesia</p>
        <a href="#about" class="btn btn-light">More About Me</a>
        <a href="/gallery" class="btn btn-light">Gallery</a>
      </div>
    </div>

    <section class="about" id="about">
      <img src="{% static './JP34-min.jpg' %}" alt="Fathan Muthahhari" />
      <div class="me">
        <h1>About Me!</h1>
        <div class="line"></div>
        <p>
          I am an active learner that always keen to learn more about how things
          work. Love anything associated with asthethic and creativity.
        </p>
      </div>
    </section>

    <div class="showcase">
      <h1>My Works So Far</h1>
      <div class="card">
        <img src="{% static './jamming.png' %}" alt="" />
        <div class="details">
          <p class="accent">Jamming</p>
          <p>App for creating and adding playlist to your Spotify account</p>
        </div>
      </div>
    </div>

    <section class="resume" id="resume">
      <div class="group">
        <h1>Education</h1>
        <table>
          <tr>
            <td class="accent">2019 - Present</td>
            <td>Faculty of Computer Science at University of Indonesia</td>
          </tr>
          <tr>
            <td class="accent">2016 - 2019</td>
            <td>SMAN 1 Bogor</td>
          </tr>
        </table>
      </div>
      <div class="group">
        <h1>Organization Experiences</h1>
        <table>
          <tr>
            <td class="accent">2020 - 2021</td>
            <td>Person in Charge of Academic BETIS 2021</td>
          </tr>
          <tr>
            <td class="accent">2020</td>
            <td>Staff of Software Engineering Academy Compfest 12</td>
          </tr>
        </table>
      </div>
    </section>

    <div class="skills">
      <h1>Skills</h1>
      <ul>
        <li>
          <span class="accent">Programming Languange</span> <br />
          Java, Python, Javascript
        </li>
        <li>
          <span class="accent">Web Development</span> <br />
          Django, ExpressJS, MongoDB, ReactJS, NodeJS, SQLite
        </li>
        <li><span class="accent">Visual Design</span></li>
      </ul>
    </div>

    <section class="contacts" id="contacts">
      <h1>Keep in Touch with Me</h1>
      <ul>
        <li>
          <a href="https://www.instagram.com/fathanmuthahhari/"
            ><i class="fab fa-instagram fa-3x"></i
          ></a>
        </li>
        <li>
          <a href="https://www.linkedin.com/in/muhammad-fathan-m-a45684130/">
            <i class="fab fa-linkedin-in fa-3x"></i
          ></a>
        </li>
        <li>
          <a href="https://github.com/Zsaschz/"
            ><i class="fab fa-github fa-3x"></i>
          </a>
        </li>
      </ul>

      <p>Email Me at: <span class="accent">fathanmuthahhari@gmail.com</span></p>
    </section>

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

story_3/templates/lab3_new_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Story 3: Muhammad Fathan Muthahhari</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static './css/all.css' %}" />
    <link rel="stylesheet" href="{% static './css/style.css' %}" />
  </head>
  <body>
    <nav>
      <ul class="menu">
        <li><a href="/#about">HOME</a></li>
        <li><a href="/#resume">RESUME</a></li>
        <li><a href="/#contacts">CONTACTS</a></li>
      </ul>
    </nav>

    <div class="gallery">
      <h1>Highlights</h1>
      <p class="accent">Good Girl</p>
      <div class="container">
        <img src="{% static './momo.jpg' %}" alt="" />
        <img src="{% static './simba.jpg' %}" alt="" />
        <img src="{% static './mole.jpg' %}" alt="" />
      </div>
      <br />
      <p class="accent">Design Portofolio</p>
      <div class="container">
        <img src="{% static './h.jpg' %}" alt="" />
        <img src="{% static './vote-13.jpg' %}" alt="" />
        <img src="{% static './djarum.jpg' %}" alt="" />
        <img src="{% static './Cover-02.jpg' %}" alt="" />
        <img src="{% static './Memes-01.jpg' %}" alt="" />
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

story_4/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Story: Muhammad Fathan Muthahhari</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static './css/all.css' %}" />
    <link rel="stylesheet" href="{% static './css/style.css' %}" />
  </head>
  <body>
    <nav>
      <ul class="menu">
        <li><a href="{% url 'story_4:index' %}">HOME</a></li>
        <li><a href="/#resume">RESUME</a></li>
        <li><a href="/#contacts">CONTACTS</a></li>
        <li><a href="{% url 'story_1:index' %}">STORY 1</a></li>
      </ul>
    </nav>

    {% block isi %}{% endblock %}

    <section class="contacts" id="contacts">
      <h1>Keep in Touch with Me</h1>
      <ul>
        <li>
          <a href="https://www.instagram.com/fathanmuthahhari/"
            ><i class="fab fa-instagram fa-3x"></i
          ></a>
        </li>
        <li>
          <a href="https://www.linkedin.com/in/muhammad-fathan-m-a45684130/">
            <i class="fab fa-linkedin-in fa-3x"></i
          ></a>
        </li>
        <li>
          <a href="https://github.com/Zsaschz/"
            ><i class="fab fa-github fa-3x"></i>
          </a>
        </li>
      </ul>

      <p>Email Me at: <span class="accent">fathanmuthahhari@gmail.com</span></p>
    </section>

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

story_5/templates/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Story: Muhammad Fathan Muthahhari</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
      <div class="container px-4">
        <a class="navbar-brand" href="#">M Fathan M</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'story_5:form' %}">Add Matkul</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'story_5:list_matkul' %}">List Matkul</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <h1 class="m-4">Detail Mata Kuliah</h1>
      <div class="d-flex flex-wrap">
            <div class="card m-4" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">{{matkul.nama}}</h5>
                <p>Dosen Pengajar: {{matkul.dosen_pengajar}}</p>
                <p>Jumlah SKS: {{matkul.jumlah_sks}}</p>
                <p>Deskripsi: {{matkul.deskripsi}}</p>
                <p>Tahun Ajar: {{matkul.tahun_ajar}}</p>
                <p>Ruang Kelas: {{matkul.ruang_kelas}}</p>
                <a href="{% url 'story_5:delete' matkul.id %}" class="btn btn-danger">Delete</a>
              </div>
            </div>
      </div>
    </div>

    <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
    ></script>
    <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
    ></script>
    <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
    ></script>
</body> 
</html>

story_5/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Story: Muhammad Fathan Muthahhari</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
      <div class="container px-4">
        <a class="navbar-brand" href="#">M Fathan M</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'story_5:form' %}">Add Matkul</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'story_5:list_matkul' %}">List Matkul</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <h1 class="my-3">Ubah List Mata Kuliah</h1>
      <form action="{% url 'story_5:list_matkul' %}" method="POST" class="form-group">
          {% csrf_token %}
          <p>Nama Mata Kuliah</p>
          <p>{{form.nama}}</p>
          <p>Nama Dosen Pengajar</p>
          <p>{{form.dosen_pengajar}}</p>
          <p>Jumlah SKS:</p>
          <p>{{form.jumlah_sks}}</p>
          <p>Deskripsi</p>
          <p>{{form.deskripsi}}</p>
          <p>Tahun Ajar: </p>
          <p>{{form.tahun_ajar}}</p>
          <p>Ruang Kelas</p>
          <p>{{form.ruang_kelas}}</p> 
          <input type="submit" value="Tambah" class="btn btn-primary">
      </form>
    </div>

    <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
    ></script>
    <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
    ></script>
    <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
    ></script>
</body> 
</html>

story_5/templates/list_matkul.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Story: Muhammad Fathan Muthahhari</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
      <div class="container px-4">
        <a class="navbar-brand" href="#">M Fathan M</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'story_5:form' %}">Add Matkul</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'story_5:list_matkul' %}">List Matkul</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <h1 class="m-4">List Mata Kuliah</h1>
      <div class="d-flex flex-wrap">
        {% if matkuls %}
            {% for matkul in matkuls%}
            <div class="card m-4" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">{{matkul.nama}}</h5>
                <p>Deskripsi: {{matkul.deskripsi}}</p>
                <a href="{% url 'story_5:detail' matkul.id %}" class="btn btn-primary">Detail</a>
                <a href="{% url 'story_5:delete' matkul.id %}" class="btn btn-danger">Delete</a>
              </div>
            </div>
            {% endfor %}
        {% endif %}
      </div>
    </div>

    <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
    ></script>
    <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
    ></script>
    <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
    ></script>
</body> 
</html>